### ISSUE TITLE
Add Support for .Net Core

### ISSUE THREAD

**Issue by bilal-fazlani** [RehanSaeed/Serilog.Exceptions#1]
Any plans to port to .net core ?

**Comment by RehanSaeed** [comment]
Yes of course. I'm waiting for the .NET Core support in Serilog to stabalize before I add it. I'd be willing to accept a PR for this.

**Comment by RehanSaeed** [comment]
Give it a try:
https://www.nuget.org/packages/Serilog.Exceptions/2.0.0-rc
