### ISSUE TITLE
Exception when logging DbEntityValidationException

### ISSUE THREAD

**Issue by rsuter** [RehanSaeed/Serilog.Exceptions#13]
When logging a `DbEntityValidationException` I get the following exception in `Log.Error(exception)`

```
Exception thrown: 'System.Reflection.TargetParameterCountException' in mscorlib.dll

Additional information: Parameter count mismatch.
```

Platform: .NET 4.5.2

Is this a known issue?

**Comment by rsuter** [comment]
The problem are indexed properties which are not correctly handled: 

![image](https://cloud.githubusercontent.com/assets/2603405/20313789/4601550e-ab58-11e6-9464-2fbe5606d4ca.png)

Adding

    .Where(x => x.CanRead && x.GetIndexParameters().Length == 0)

fixes this, but indexed properties are ignored...

**Comment by rsuter** [comment]
Created PR: https://github.com/RehanSaeed/Serilog.Exceptions/pull/14

**Comment by arnolddg** [comment]
also solves [issue 12](https://github.com/RehanSaeed/Serilog.Exceptions/issues/12) I think.

**Comment by hardcodet** [comment]
Unrelated to this very case, logging MUST NOT crash. Never. Seeing this just made me skip the whole project - I simply cannot affort my logging pipeline to crash with an exception and thus make me blind to potentially critical production issues (since I would have never observed them in dev/test). Whatever the framework does, everything should be in a try/catch block with a fallback...

Just my 0.02$
Philipp

**Comment by rsuter** [comment]
The exception is catched and the additional property is just not generated and appended...

**Comment by hardcodet** [comment]
Awesome - I misinterpreted the post then. Thanks for the clarification!

**Comment by RehanSaeed** [comment]
Apologies for not getting on top of this earlier. I was on holiday and later got distracted by life. I've now merged both PR's. Can you confirm everything works using the MyGet package and I'll arrange a release.

**Comment by RehanSaeed** [comment]
I guess closing the issue means that all works well?

**Comment by rsuter** [comment]
I didnt test the myget package (feed url?) but I already use the PRs in production code and it works for me..
