### ISSUE TITLE
disable reflection based destructurer 

### ISSUE THREAD

**Issue by 304NotModified** [RehanSaeed/Serilog.Exceptions#156]
Hi,

As far as I understand, disabling/replacing the reflection based destructurer isn't an option.

(see also https://stackoverflow.com/questions/59054681/is-it-possible-to-disabled-the-reflection-based-destructurer-in-serilog-exceptions)

Is a PR accepted for this?

**Comment by krajek** [comment]
Hi @304NotModified, thanks for reaching out.

You are right, this is not an option yet. Nobody asked for it and we did not think about it :-).

I am pretty sure that we would agree on backward-compatible change that would allow disabling reflection-based destructurer.

I think I can implement it early next week.

**Comment by 304NotModified** [comment]
Cool!

**Comment by RehanSaeed** [comment]
Fixed in https://github.com/RehanSaeed/Serilog.Exceptions/pull/158

**Comment by RehanSaeed** [comment]
5.4.0 released.

**Comment by 304NotModified** [comment]
Great!
