### ISSUE TITLE
Exception Destructuring blows up when IDictionary is generic

### ISSUE THREAD

**Issue by optical** [RehanSaeed/Serilog.Exceptions#17]
When `ExceptionDestructurer.Destructure` is invoked with an Exception that has a `.Data` property that returns a generic dictionary, eg `Dictionary<string, object>`, an invalid cast exception is raised. This is because it attempts to cast a KeyValuePair to a DictionaryEntry. See [code](https://github.com/RehanSaeed/Serilog.Exceptions/blob/master/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs#L201)

See this example for a case where the destructurer fails: https://gist.github.com/optical/6e47c7e46fbba839ab22ba92c0d536ee

Many Custom exceptions don't return a non generic dictionary. For example, Npgsql's NpgsqlException does [this](https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/PostgresException.cs#L246)

It seems like the destructurer should handle this more gracefully

**Comment by RehanSaeed** [comment]
I'll take a look after we merge your VS 2017 PR. Thanks for all your hard work!

**Comment by RehanSaeed** [comment]
Please check My-Get (See front page for link) for your fix. Will release to NuGet if all is well.

**Comment by optical** [comment]
Thanks for this - Will give a spin next week.

**Comment by optical** [comment]
@RehanSaeed I've given this a quick test locally and its now successfully handling the exceptions it was failing on :+1:
