### ISSUE TITLE
Rolling FIles creating more than one log file per date

### ISSUE THREAD

**Issue by Des-Angelo** [RehanSaeed/Serilog.Exceptions#22]
When a new exception is logged, a new file is created.

Scenario:
First file created: 
**log-20170602**

Files created per exceptions: 
**log-20170602_001
log-20170602_002
log-20170602_003**

My code (C# - Visual Studio 2015 Project):
```
public class EventLogging
    {
        private readonly Logger _logger;


        public EventLogging(IOptions<LoggingOptions> logOption)
        {
            var logAccessor = logOption.Value;

            _logger = new LoggerConfiguration()
                .Enrich.WithExceptionDetails()
                .WriteTo.Sink(new RollingFileSink(logAccessor.Path,
                    new JsonFormatter(renderMessage: true), null, null)).CreateLogger();
        }

        public void LogError(string message, Exception exception)
        {
            _logger.Error(exception, message);
        }

        public void LogWarning(string message, Exception exception)
        {
            _logger.Warning(exception, message);
        }
    }
```
Refer that class to avoid  writing the following code in every class:
```
_logger = new LoggerConfiguration()
                .Enrich.WithExceptionDetails()
                .WriteTo.Sink(new RollingFileSink(logAccessor.Path,
                    new JsonFormatter(renderMessage: true), null, null)).CreateLogger();
```
Is there a way to prevent the files being created per exception but per new date.

**Comment by nblumhardt** [comment]
Hi @Des-Angelo  - you need to create only a single logger attached to the file, and share it between all of the classes that use it: https://github.com/serilog/serilog/wiki/Lifecycle-of-Loggers

HTH!
Nick

**Comment by Des-Angelo** [comment]
Hey @nblumhardt - Totally overlookedthe wiki link that serilog has a global log class I can just configure in the configure method in startup.cs. Thanks for your help. However:

 `Log.Error("Some Message", ex)`

Does not have details of the exceptions such as stacktrace, message, etc.

`Log.Logger = new LoggerConfiguration()
                .Enrich.WithExceptionDetails()
                .WriteTo.Sink(new RollingFileSink(Configuration.GetValue<string>("EventLogging:Path"), new JsonFormatter(renderMessage: true), null, null))
                .CreateLogger();`

Above is the code for configuration.

**Comment by Des-Angelo** [comment]
Hey @nblumhardt - Totally overlookedthe wiki link that serilog has a global log class I can just configure in the configure method in startup.cs. Thanks for your help.
