### ISSUE TITLE
Guidance on how to go about in filtering out certain properties

### ISSUE THREAD

**Issue by tputs001** [RehanSaeed/Serilog.Exceptions#231]
### Question

I'm trying to control the properties that Serilog.Exception is generating and sending back to our Kibana.  I want to just keep the top level that Serilog.Exception generates.  Can you help provide some guidance on how to filter out properties like `InnerException` and `Call` ?

I think I can use the `WithFilter(someFilter)` method, but I'm not sure what `some filter` is suppose to be.  I was trying to find some examples but I can't find any.  I also tried to control the DestructuringDepth by setting it to 1, but it seems to still go several layers deep.

Any help would be greatly appreciated, thank you.

![image](https://user-images.githubusercontent.com/528146/91371388-b20d2180-e7c5-11ea-8890-71447e6c24c9.png)

**Comment by krajek** [comment]
HI @tputs001 

In general, `DestructuringDepth`, should be the way to go. Note, that it works only for the reflection-based restructured. 

As for ignoring certain properties, we have `IgnorePropertyByNameExceptionFilter`, you just pass properties names to the constructor.

Could you post a minimal and complete example of the issue you mentioned? 
It would be so much easier to diagnose and advise.

**Comment by tputs001** [comment]
Hi @krajek 

Thank you for the quick response. I actually am going to close this issue, I managed to figure it out.  Thank you again!
