### ISSUE TITLE
Remove System.Data.SqlClient dependency

### ISSUE THREAD

**Issue by shatl** [RehanSaeed/Serilog.Exceptions#27]
Please extract SqlException destructurer to separate. 
There are lots of cases when application does not have a dependency on SQL Server.

Another option is to use reflection to lookup for properties.

Thanks

**Comment by RehanSaeed** [comment]
I agree with your sentiment. When I started this project for use in the company I work for, SQL was a requirement. I would like destructurers to be more pluggable generally. For every DLL in the .NET Core Framework, my thinking was that I'd create a mirror DLL containing destructurers. If you wanted all destructurers, you could use a meta package that referenced them all a bit like how ASP.NET Core does it with `Microsoft.AspNetCore.All`.

The only issue is that I don't have time to implement this major feature.

**Comment by shatl** [comment]
@RehanSaeed I moved destructurer to separate assembly.
Could you check/update build scripts?

Thanks

**Comment by RehanSaeed** [comment]
I use Cake for build scripts. The cool think is, the [script](https://github.com/RehanSaeed/Serilog.Exceptions/blob/master/build.cake) is so generic, it still works with your changes.

Have reviewed your changes. One issue but will merge and release soon.

**Comment by shatl** [comment]
Thanks @RehanSaeed . Can yuo push this to nuget?

**Comment by RehanSaeed** [comment]
It's on it's way.
