### ISSUE TITLE
Serious performance issue in combination with dbsets in dbcontext

### ISSUE THREAD

**Issue by mkeymolen** [RehanSaeed/Serilog.Exceptions#275]
The logging causes a very important performance drain in combination with dbsets in you dbcontext.
If an error occurs at dbcontext level, it tries to log the Dbcontext class and al its properties. 
If you have dbsets configured in that dbcontext class it will load all data from each table which wil cause a cpu/memory/database crash if it is a large database. 

If i have time soon, i will try to solve it via a PR

**Comment by RehanSaeed** [comment]
This is called out in the main README. You need to use this additional package with EF Core:
https://github.com/RehanSaeed/Serilog.Exceptions#serilogexceptionsentityframeworkcore
