### ISSUE TITLE
Stack Trace Property Missing

### ISSUE THREAD

**Issue by SteGaff7** [RehanSaeed/Serilog.Exceptions#288]
### Describe the bug

My understanding from [Issue 29](https://github.com/RehanSaeed/Serilog.Exceptions/issues/29) was that excluding the stack trace property was an optional filter, however for me it seems to be excluding it by default.

I am using the Google Cloud Logging sink, injecting Serilog logger and using the Microsoft ILogger interface. 

It would be great to get some clarity if this property is ignored by default and if so, is it possible to include it once again?

**Comment by RehanSaeed** [comment]
Yes this is the default behaviour. We skip the StackTrace in the Serilog.Exception's exception details because it's already included with the default Serilog log message.

**Comment by RehanSaeed** [comment]
See https://github.com/RehanSaeed/Serilog.Exceptions#filtering-properties for how to change the default.

**Comment by SteGaff7** [comment]
Thanks for the information.
