### ISSUE TITLE
Be able to exclude the StackTrace

### ISSUE THREAD

**Issue by WayneHiller** [RehanSaeed/Serilog.Exceptions#29]
It would be nice to be able to exclude the StackTrace because SeriLog already includes that and the duplication can get quite large.

**Comment by RehanSaeed** [comment]
Thats a decent idea. I'm too busy to look at this at the moment but I will accept a PR.P Perhaps we should also include the message?

**Comment by WayneHiller** [comment]
I can do it. I Cloned it and just commented out the StackTrace Line for myself.  It would probably be good to have both the StackTrace and the Message as optional. Usually there is no reason to duplicate them.  I really noticed it when viewing events in Seq.

**Comment by RehanSaeed** [comment]
Maybe we should omit them as you say. Is there any reason at all they might be useful? I can't think of any, except that it groups all properties in one place.

**Comment by WayneHiller** [comment]
I can't really think of any either. Both properties will always be included in all the events anyway. Only maybe if someone was doing a custom display of events or something. Would be very rare.

**Comment by JeroenDragt** [comment]
I am currently trying to create a filter so you can exclude the properties that you do not want when configuring your logger, would that be a good way to approach this issue?

**Comment by WayneHiller** [comment]
That would probably work the best.

**Comment by JeroenDragt** [comment]
@RehanSaeed  I have created the filter, but I am unable to create a branch, and can therefore not sumbit a pull request. Can you grant me the required access rights?

**Comment by nblumhardt** [comment]
@JeroenDragt you'll need to use the "Fork" button at the top of the page to create your own fork, from which you can submit a PR.

**Comment by JeroenDragt** [comment]
Ah, thanks. I submitted the pull request :)

**Comment by RehanSaeed** [comment]
@JeroenDragt I've taken a look at your [pull request](https://github.com/RehanSaeed/Serilog.Exceptions/pull/32) and you've added the ability to turn off the logging of any property and not just the StackTrace and Message properties. I'm not sure that this is something that people would want to do. At least, I can't think of a reason to do it off the top of my head and it adds complexity to all of the exception destructurers.

In my head I was thinking of just adding two flags to the `ExceptionDestructurer` that all destructurers inherit from to turn off logging `Message` and `StackTrace` properties as those are the only duplicates. I'm leaning towards leaving them on by default but I'm open to a discussion on that.

**Comment by JeroenDragt** [comment]
@RehanSaeed The reason why i added the ability to ignore any property was because in some of our logging we have fields that are so big that it obscures the rest of the logged properties. For example when logging an entity framework exception, one of the logged properties contained a breakdown of all the settings of each field of a database table, which resulted in a property of over a 1000 lines, that did not really tell us anything. 
My solution might add some more complexity, but if another issue is created in the future that asks if another property can be ignored, you don't have to add another flag.

**Comment by RehanSaeed** [comment]
@JeroenDragt What are you using to store and view your logs? Is that a custom exception or one built into .NET? One solution would be to just create a custom destructurer for that special exception.

**Comment by JeroenDragt** [comment]
@RehanSaeed I'm using the ELK (Elasticsearch, Logstash, Kibana) stack for logging. The exception in question is not a standard .NET exception, but from a third party library called Entity Framework. I could make a custom destructurer, but I feel my solution adds more flexibility and would save people time, because they would not have to make a custom destructurer every time they want to log a third party exception in a non-standard way.

**Comment by WayneHiller** [comment]
Allowing any property to be excluded would be the most flexible approach.

**Comment by JeroenDragt** [comment]
So @RehanSaeed, what do you think?

**Comment by RehanSaeed** [comment]
Apologies for the delay, I haven't been very good at pushing through this PR. I've been away for a while.

This is a feature needed in special circumstances, there is a performance cost to this feature. As an example, the `AggregateExceptionDestructurer` is very simple and the cost is doing `List<T>.Contains` for ever property in the exception. The reflection destructurer, the cost as compared to the very slow reflection is much lower but it could be looking at a lot more properties too.

What if we created a derived type of the `ReflectionBasedDestructurer` which adds this ability? I'll go with the concensus in this issue and try to get this out fairly quickly, as long as I don't get hit by a bus.

**Comment by JeroenDragt** [comment]
Ok, that sounds good!

**Comment by krajek** [comment]
In general, I like the idea of the generic functionality of ignoring properties.

Regarding performance, obviously, there is a tradeoff but:
* I assume it would be an option, disabled by default, only those who use it will pay for it
* performance of lookup operation may be improved, for example using TRIE
* last but not least, in some sense, performance is not critical for exception logging library, it seems to me that linear cost with tiny constant factor is acceptable

That said, I have to admit, I am not 100% sure we should do it this way, more like 80% ;-).

**Comment by RehanSaeed** [comment]
Totally agree with your first two points. On your third point, in my experience exceptions tend to be raised in bulk when they happen e.g. database goes down, now you have thousands of exceptions. In this scenario, logging takes a lot of processing time as you are processing logs of a large size and number, so I think performance is a problem with logging in general. This package tries to partially solve that trying to avoid use of reflection for common exception types in the BCL.

**Comment by WayneHiller** [comment]
I agree that using Reflection should always be a last resort due to performance.  At the same time excluding properties that you are not interested in cuts down on network traffic and storage space. I think as long as "Property Filtering" is off by default it would work ok.

**Comment by RehanSaeed** [comment]
Cool, thanks for feedback everyone.

I've asked for one optimization to be made to the PR. If there are no ignored properties, the property is added as normal and we pay no cost. 

I'll merge the PR as soon as I can after that.

**Comment by krajek** [comment]
I resigned from the PR #35 because of its flawed design. I will come back with a better solution.
