### ISSUE TITLE
NuGet feed DLL needs to be strong-named

### ISSUE THREAD

**Issue by slapperjoe** [RehanSaeed/Serilog.Exceptions#3]
Hi,
The current Serilog.Exceptions package up in Nuget isn't strong-named which obviously causes issues.  Esp. when other serilog packages are signed.  It would be good if this package was also followed suit.

**Comment by joelweiss** [comment]
Try using [Strong Namer](https://github.com/dsplaisted/strongnamer) to sign Serilog.Exceptions during the build process.

**Comment by RehanSaeed** [comment]
Give it a try
https://www.nuget.org/packages/Serilog.Exceptions/2.0.0-rc
