### ISSUE TITLE
[Docs] Destructurer via json

### ISSUE THREAD

**Issue by lonix1** [RehanSaeed/Serilog.Exceptions#300]
I have all my config in json. Does anyone know how to use the destructurer via json?

For example, for [`Serilog.Exceptions.EntityFrameworkCore`](https://github.com/RehanSaeed/Serilog.Exceptions#serilogexceptionsentityframeworkcore):
````cs
.Enrich.WithExceptionDetails(
  new DestructuringOptionsBuilder()
  .WithDefaultDestructurers()
  .WithDestructurers(new[] { new DbUpdateExceptionDestructurer() })
)
````

How is that represented in the `appsettings.json`?

It would also be useful to add that to the docs in the corresponding section.

**Comment by RehanSaeed** [comment]
See https://github.com/RehanSaeed/Serilog.Exceptions/issues/58 for a bit more info. We don't currently support serilog-settings-configuration. It would be a nice addition. If you'd like to suggest an idea with a PR, we'd consider it.

**Comment by lonix1** [comment]
I wouldn't know how :) I realise you can't support every config scenario though! Feel free to close.

---

BTW I'm confused about the comment in that other issue about how most modern systems use config in code rather than json. The serilog authors also have that opinion.

But in small environments (few people) or when you're working alone, you don't have tools and time to do things "properly". So you deploy to production and tweak config files by hand if you need to. The advice against this is only sensible for large teams/companies with CI.

Anyways, thanks for this very useful plugin, it's appreciated!

**Comment by RehanSaeed** [comment]
I went on the same search as you for using JSON and came to the same realization.
