### ISSUE TITLE
Add configuration example to readme

### ISSUE THREAD

**Issue by MNF** [RehanSaeed/Serilog.Exceptions#323]
It will be good to add to readme an example of configuration as an alternative to hardcoded new LoggerConfiguration() .Enrich.WithExceptionDetails()- something like

{
  "Serilog": {
    "MinimumLevel": "Debug",
    "Using":  [ "Serilog.Exceptions" ],
    "Enrich": [ "WithExceptionDetails"],
    "WriteTo": [
      { "Name": "Console" }
    ]
  }
}

I haven’t tried it yet.
 Will it work ?

**Comment by RehanSaeed** [comment]
It should work. Will accept a PR!
