### ISSUE TITLE
Support Demystifier?

### ISSUE THREAD

**Issue by RSuter** [RehanSaeed/Serilog.Exceptions#33]
Better async stacktraces. See https://github.com/benaadams/Ben.Demystifier

**Comment by nblumhardt** [comment]
@RSuter if you plug in https://github.com/nblumhardt/serilog-enrichers-demystify you'll get clean stack traces from this package 👍 

(Still a fairly experimental out-of-band component while we learn the ropes, but eventually something I hope Serilog itself can buy into :-))

**Comment by RehanSaeed** [comment]
That new package is pretty cool, I'll be adding that to my apps today too!

**Comment by RSuter** [comment]
Ah, I think Serilog.Exceptions is only for serializing additional properties and does not log StackTraces itself? Then using Serilog.Enrichers.Demystify makes sense...

**Comment by RehanSaeed** [comment]
That is correct. For reasons that I shall never understand doing a `ToString()` on an exception does not output all the information in an `Exception` object. `Serilog.Exceptions` tries to solve that without reflection in some cases but falls back to reflection for uncommon and esoteric exceptions.
