### ISSUE TITLE
Separated Column or Porperty for exception stacktrace

### ISSUE THREAD

**Issue by Brunoporto2702** [RehanSaeed/Serilog.Exceptions#342]
### Considering the use of structured logs in order to ease processing the logs and being able to generate more precise errors and performance reports:

I was woundering if it would be possible to implement a new property of the current output object that consists of the file and function where the exception occured in order to facilitate post processing the log, for example to create a Dashboard with the most problematic part of the system. 

Rigth now, I am able to log the entire exception, but that is not of grate help, once sometimes there are a lot more information than it's needed and parsing those informations before presenting it to the user is may not be a good solution from a performance perspecitve. 

It would good if it were possible to integrate with others sinks options available in serilog library. 

Maybe there is already a way of acchieving such result, and I may be not aware of. If that's the case, please disconsider the issue, but still would be good to discuss it with the comunity!

Thanks in advance for the attention!

Cheers!

**Comment by RehanSaeed** [comment]
The StackTrace should give you information about where the exception came from. Is there something else you need?

**Comment by RehanSaeed** [comment]
Feel free to reopen if you have more information.
