### ISSUE TITLE
Add destructurer for Refit ApiException

### ISSUE THREAD

**Issue by git-heath** [RehanSaeed/Serilog.Exceptions#396]
### Describe the feature

Certain useful properties in the Refit.ApiException class are not logged automatically by Serilog. E.g: Uri, StatusCode, Content etc.

**Comment by krajek** [comment]
Can you post a source code with a[ minimal and complete example](https://stackoverflow.com/help/minimal-reproducible-example) ?

**Comment by git-heath** [comment]
Yes absolutely, this was my aim. Will post later today.

**Comment by git-heath** [comment]
@krajek  could you please add me as a contributer to this repo as my attempts to push my branch are rejected with a 403 error ? If this doesn't make sense to you, don't worry the issue could also be on my side.

**Comment by krajek** [comment]
@git-heath no, we will not add you as a contributor at that time.
Do you know you can fork the repository and open a pull request? This is the standard way to contribute.

That said, I do not expect your example to be related to this repo.
You can prepare a failing test or just a simple problem that demonstrates your issue.
