### ISSUE TITLE
EF6 - protection against logging entire db.

### ISSUE THREAD

**Issue by statler** [RehanSaeed/Serilog.Exceptions#424]
With reference to https://github.com/RehanSaeed/Serilog.Exceptions#serilogexceptionsentityframeworkcore. do you know if there is a similar issue with EF6? I have experience with this in EFCore, and wanted to make sure the same issue wont arise in EF6 if you happen to be across it.

**Comment by RehanSaeed** [comment]
There should no longer be any issue. Fixed by https://github.com/RehanSaeed/Serilog.Exceptions/pull/425.
