### ISSUE TITLE
Entity Framework Logging Behaviour

### ISSUE THREAD

**Issue by statler** [RehanSaeed/Serilog.Exceptions#439]
### Describe the bug

The docs describe the known issue with logging of the whole database as below:

_WARNING: In older versions of Serilog.Exceptions, if you are using EntityFrameworkCore with Serilog.Exceptions you must add this, otherwise in certain cases your entire database will be logged! This is because the exceptions in Entity Framework Core have properties that link to the entire database schema in them (See #100, aspnet/EntityFrameworkCore#15214). Newer versions of Serilog.Exceptions avoids this issue by preventing the destructure of properties that implement IQueryable preventing their execution._

**_In older versions of Serilog.Exceptions_** Can you please clarify what versions this is necessary for.  'Older versions' is not definitive or informative. Is it still a requirement or not.

### Steps to reproduce

View the docs

### Expected behaviour

The requirement for what versions the additional library is required for should be explicit, or at least definitive about whether the issue is present in the current build.

**Comment by RehanSaeed** [comment]
This was the PR that had the fix in it:

- https://github.com/RehanSaeed/Serilog.Exceptions/pull/425

This made it into the 8.0.0 release:

- https://github.com/RehanSaeed/Serilog.Exceptions/releases/tag/8.0.0

Documentation updated.

**Comment by statler** [comment]
Superb. Thank you for your work
