### ISSUE TITLE
Allow to configure depth of destructuring

### ISSUE THREAD

**Issue by krajek** [RehanSaeed/Serilog.Exceptions#47]
For now, reflection destructurer depth traversal is hardcoded to 10, I think it would be a good idea to allow configuration for the field. `Serilog` has that and more in form of `Destructure.ToMaximumDepth(n)`.
What do you think about that?
My dream solution is to be using `Serilog` configuration directly and support all the limits that `Serilog` does(collection length, string length).

**Comment by RehanSaeed** [comment]
I think we need a settings class where we can include this and the name of the property `ExceptionDetail` to satisfy https://github.com/RehanSaeed/Serilog.Exceptions/issues/38.

**Comment by krajek** [comment]
Closed by #49.
