### ISSUE TITLE
Maximum destructuring depth reached.

### ISSUE THREAD

**Issue by codehunter13** [RehanSaeed/Serilog.Exceptions#496]
### Describe the bug

When i use WithExceptionDetails and log a System.AggregateException (DbUpdateException),  i get the error "Maximum destructuring depth reached" from serilog selflog. Is there a way to solve this?

Thx in advance

### Steps to reproduce

WithExceptionDetails 
System.AggregateException (DbUpdateException)

### Expected behaviour

No Maximum destructuring depth reached messages

**Comment by RehanSaeed** [comment]
What does your exception look like? For some exception types we fallback to using reflection and to avoid doing too much we have to add limits. It sounds like your exeption has multiple nested properties.

**Comment by RehanSaeed** [comment]
Feel free to reopen with more info.
