### ISSUE TITLE
Insert data from ex.data into output template

### ISSUE THREAD

**Issue by bxbxbx** [RehanSaeed/Serilog.Exceptions#50]
I tried the following but can't get it to work.

var ex = new InvalidOperationException("SubJob {SubJobId} Status<>Startable");
ex.Data.Add("SubJobId", subJobId);

_logger.Fatal(ex, ex.Message);

But the Property is not replaced in the output, it seems that I'm doing something wrong, or is this not feasible?

Can you please offer some advice?

**Comment by krajek** [comment]
Hi @bxbxbx.

There are two major problems with your approach, let me explain each one separately.

The first issue is that exception message is not a template for `Serilog`. Whether you are using `Serilog.Exceptions` or not is not relevant. 

The second issue is that you do not have to and, in fact, you should never pass `ex.Message` to as a `messageTemplate` argument of `Serilog's` log method. The proper way to use `Serilog` in ypur case would be:
```
var ex = new InvalidOperationException($"SubJob Status<>Startable");
ex.Data.Add("SubJobId", subJobId);
_logger.Fatal(ex, "There was a problem with SubJob with id {SubJobId}, subJobId);
```

Notice that `Fatal` method is accepting a proper `messageTemplate` and a parameter to fill the placeholder. On the other hand, the exception message is not a template, so there is no placeholder.

Is there anything else I could explain?

**Comment by bxbxbx** [comment]
Hello @krajek 

thx for your elaborate answer. 
This is a legacy project, so no IoC yet, but I'm working on that.
I was thinking that this was a way to avoid passing around the logger all the time, but I guess I will have to.

bye!
