### ISSUE TITLE
Document every public object in the library

### ISSUE THREAD

**Issue by krajek** [RehanSaeed/Serilog.Exceptions#52]
Before 4.0 I want to make sure that every public facing element of API is well documented.

**Comment by RehanSaeed** [comment]
That would be excellent. I tend to use GhostDoc in combination with turning on the documentation file in the csproj and the StyleCop documentation rules.

**Comment by krajek** [comment]
Open questions:
A) Should we make `WithExceptionDetails(destructurers)` obsolete and direct users to new fluent API? I think that we should.
B) Should we make the WithIgnoreStackTraceAndTargetIdExceptionFilter a default? I think yes, seems like users do not need `StackTrace` to be duplicated. I am open for discussion.
C) Why this method extension method exists? It does not seem to contain anything specific to `Serilog.Exceptions`
```
public static Serilog.LoggerConfiguration WithProperties(
            this LoggerEnrichmentConfiguration loggerEnrichmentConfiguration,
            IDictionary<string, object> properties)
```

@RehanSaeed what do you think about each topic?

**Comment by RehanSaeed** [comment]
a. Yes
b. Yes
c. I added this at the time because it was useful to me but yes I agree that it does not fit in with this project.

**Comment by RehanSaeed** [comment]
Consider removing the lines related to comments [here](https://github.com/RehanSaeed/Serilog.Exceptions/blob/87ec6382060fb8374e1f93d3969e1dd772133958/MinimumRecommendedRulesWithStyleCop.ruleset#L71)
