### ISSUE TITLE
Add support for serilog-settings-configuration

### ISSUE THREAD

**Issue by RehanSaeed** [RehanSaeed/Serilog.Exceptions#58]
I've just realized that our builder code will not work with [serilog-settings-configuration](https://github.com/serilog/serilog-settings-configuration). We should additionally provide an overload which works with this package which looks at the parameter names I think, need to investigate more.

cc @krajek

**Comment by krajek** [comment]
I took a quick look and there are two ways in which Serilog.Settings.Configuration can be used.
One is to use the default `WithExceptionDetails` with no arguments.
Second is to use some class implementing our configuration interface, with default constructor which can be used in the configuration file. Of course, the second method is obscure.

For 4.1 I will prepare a small PR that will expose new API with all available configuration parameters.

**Comment by fleed** [comment]
@RehanSaeed @krajek Any progress here?

**Comment by RehanSaeed** [comment]
No but we'd be willing to accept a PR for this.

**Comment by krajek** [comment]
@RehanSaeed the issue is so old and yet nobody complained. At the time I thought that it would be useful but it seems configuration in code is the standard. 

My suggestion: close the ticket.
