### ISSUE TITLE
Demystified exception stack trace support

### ISSUE THREAD

**Issue by abrasat** [RehanSaeed/Serilog.Exceptions#586]
Does the Serilog.Exceptions library support also demystified exception stack traces? Or must an application use this library together with some additional enricher as [serilog enricher demystifier](https://github.com/Megasware128/serilog-enrichers-demystifier)? I mean something like this:

```
Log.Logger = new LoggerConfiguration()
    .Enrich.WithDemystifiedStackTraces()
    .Enrich.WithExceptionDetails()
...
```
Is the order of adding the enrichers important, or it does not make any difference?

**Comment by RehanSaeed** [comment]
You can use that separate package to include a better stack trace. This package does not change the stack trace.
