### ISSUE TITLE
Race Condition in ReflectionBasedDestructurer

### ISSUE THREAD

**Issue by shatl** [RehanSaeed/Serilog.Exceptions#59]
`reflectionInfoCache` is not thread-safe.

See https://github.com/RehanSaeed/Serilog.Exceptions/blob/master/Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs#L319

**Comment by krajek** [comment]
Hey @shatl. Yes, you are absolutely right.
Do you think that it is a problem? Should sinks be thread safe? Is it documented somewhere?
I am sincerely curious, I haven't yet found such explanation.

**Comment by shatl** [comment]
Good question to ask on Serilog project page :)
I'd say it is more about Enrichers, not Sinks. 
Since this Destructurer has the state, I'd be very careful about multi-threading. 

Looking at https://github.com/serilog/serilog/blob/96bfe61c7e35271450062846374c13cce75b83e5/src/Serilog/Core/Logger.cs#L408 I did not found any code enforcing single threading on enrichers.

**Comment by krajek** [comment]
@shatl Thanks a lot, for mentioning the issue. I have just added simple `lock` in a critical section so that `ReflectionBasedDestructurer` is now thread-safe. The fix is released as part of `4.1.0`.

**Comment by krajek** [comment]
@RehanSaeed could you please publish `4.1.0` nuget package?

**Comment by johnrutherford** [comment]
I was investigating high CPU usage on our web servers. The report from DebugDiag linked to this post: [High CPU in .NET app using a static Generic.Dictionary](https://blogs.msdn.microsoft.com/tess/2009/12/21/high-cpu-in-net-app-using-a-static-generic-dictionary/). This was the relevant stack trace:

```
mscorlib_ni!System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].FindEntry(System.__Canon)+ee
mscorlib_ni!System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].TryGetValue(System.__Canon, System.__Canon ByRef)+14
Serilog.Exceptions.Destructurers.ReflectionBasedDestructurer.DestructureObject(System.Object, System.Type, Int32, System.Collections.Generic.IDictionary`2>, Int32 ByRef)+10c
Serilog.Exceptions.Destructurers.ReflectionBasedDestructurer.Destructure(System.Exception, Serilog.Exceptions.Core.IExceptionPropertiesBag, System.Func`2>)+86
Serilog.Exceptions.Core.ExceptionEnricher.DestructureException(System.Exception)+107
Serilog.Exceptions.Core.ExceptionEnricher.Enrich(Serilog.Events.LogEvent, Serilog.Core.ILogEventPropertyFactory)+3a
Serilog.Core.Enrichers.SafeAggregateEnricher.Enrich(Serilog.Events.LogEvent, Serilog.Core.ILogEventPropertyFactory)+5b
Serilog.Core.Logger.Dispatch(Serilog.Events.LogEvent)+39
Serilog.Core.Sinks.SecondaryLoggerSink.Emit(Serilog.Events.LogEvent)+131
Serilog.Core.Sinks.SafeAggregateSink.Emit(Serilog.Events.LogEvent)+53
Serilog.Core.Logger.Write(Serilog.Events.LogEventLevel, System.Exception, System.String, System.Object[])+131
Serilog.Core.Logger.Error(System.Exception, System.String)+26
...
```

It looks like this change to make the `ReflectionBasedDestructurer` will resolve our high CPU issue. Thanks!

**Comment by krajek** [comment]
Thanks for sharing the info. It is always informative to see such problems in the wild.
