### ISSUE TITLE
StyleCop Rules Enabled?

### ISSUE THREAD

**Issue by Mike-EEE** [RehanSaeed/Serilog.Exceptions#9]
It appears when I upgrade to Serilog.Exceptions 2.2.0, it adds StyleCop analysis to my solution.  All sorts of warnings are appearing now when I build my projects.  Is this a known issue, by chance?

**Comment by RehanSaeed** [comment]
Published 2.2.1. Sorry for the error on my part.

**Comment by Mike-EEE** [comment]
Awesome!  Glad to see that I am not crazy for once. 😛   Thank you for being so quick to fix this!
