### ISSUE TITLE
Log certain ExceptionDetail fields to separate database table columns

### ISSUE THREAD

**Issue by nilmas** [RehanSaeed/Serilog.Exceptions#96]
I'm using Serilog.Sinks.Postgresql (https://github.com/b00ted/serilog-sinks-postgresql) and I would like to log certain fields from the ExceptionDetail object to separate database table columns.

In Serilog.Sinks.Postgresql context this would mean using SinglePropertyColumnWriter. As an example from https://github.com/b00ted/serilog-sinks-postgresql:

IDictionary<string, ColumnWriterBase> columnWriters = new Dictionary<string, ColumnWriterBase>
{
...
    {"machine_name", new SinglePropertyColumnWriter("MachineName", PropertyWriteMethod.ToString, NpgsqlDbType.Text, "l") },
...
};

I'm hoping to accomplish something like this with Serilog.Exceptions together with Serilog.Sinks.Postgresql:

IDictionary<string, ColumnWriterBase> columnWriters = new Dictionary<string, ColumnWriterBase>
{
...
    {"exception_source", new SinglePropertyColumnWriter("ExceptionDetail.Source **[or ExceptionDetailSource]**", PropertyWriteMethod.ToString, NpgsqlDbType.Text, "l") },
    {"exception_source", new SinglePropertyColumnWriter("ExceptionDetail.Type", PropertyWriteMethod.ToString, NpgsqlDbType.Text, "l") },
    {"exception_source", new SinglePropertyColumnWriter("ExceptionDetail.HResult", PropertyWriteMethod.Raw, NpgsqlDbType.Integer) },
    {"exception_source", new SinglePropertyColumnWriter("ExceptionDetail.Message", PropertyWriteMethod.ToString, NpgsqlDbType.Text, "l") },
...
};

Is this currently possible with Serilog.Exceptions or could it be part of it in the future or better left for individual use case in which case, any examples?

**Comment by krajek** [comment]
I am not familiar with PostgreSql sink, but in general, `ExceptionDetail` property generated by `Serilog.Exceptions` is a normal property that can be consumed just like any other. Therefore, any specific issues are much better suited for the sink's repository rather than this one. 

That said it seems that the sink has some writers for JSON payloads, which in that your case may be beneficial. If you want to write properties of destructured exceptions to the database JSON maybe more versatile, since the structure of `ExceptionDetails` is dependent on the exception type.

**Comment by nilmas** [comment]
Appreciate the response.

I was thinking something along these lines for extracting "always there" Exception properties from ExceptionDetail and adding them directly to log event properties to be written to separate database columns:

        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            if (logEvent.Exception == null) return;
            if (!logEvent.Properties.TryGetValue("ExceptionDetail", out var value)) return;
            var dic = value as DictionaryValue;
            if (dic == null) return;

            if (dic.Elements.TryGetValue(SourceScalar, out var sourceValue))
            {
                _cachedSource = _cachedSource ?? propertyFactory.CreateProperty(ExSource, sourceValue.ToString("l", null), false);
                logEvent.AddPropertyIfAbsent(_cachedSource);
            }

            if (dic.Elements.TryGetValue(TypeScalar, out var typeValue))
            {
                _cachedType = _cachedType ?? propertyFactory.CreateProperty(ExType, typeValue.ToString("l", null), false);
                logEvent.AddPropertyIfAbsent(_cachedType);
            }

            if (dic.Elements.TryGetValue(HResultScalar, out var hresultValue) && int.TryParse(hresultValue.ToString(), out var hresult))
            {
                _cachedHresult = _cachedHresult ?? propertyFactory.CreateProperty(ExHresult, hresult, false);
                logEvent.AddPropertyIfAbsent(_cachedHresult);
            }

            if (dic.Elements.TryGetValue(MessageScalar, out var messageValue))
            {
                _cachedMessage = _cachedMessage ?? propertyFactory.CreateProperty(ExMessage, messageValue.ToString("l", null), false);
                logEvent.AddPropertyIfAbsent(_cachedMessage);
            }
        }
