### ISSUE TITLE
Properties are written in PascalCase

### ISSUE THREAD

**Issue by axbutler** [RehanSaeed/Serilog.Exceptions#99]
Hi

Thank you for this excellent library which I am just getting to grips with.

I have an issue in that the property names are PascalCase where the standard serilog exception properties are camelCase - at least in elastic search which is my use case.

Is there a way to get them to follow the normal convention and also be camelCase?
Also, any way to merge them with the standard exception properties logged by serilog itself?
It seems a bit odd to have exception.foo, exception.bar etc and then a completely separate section with exceptionDetail.baz etc...

thanks

**Comment by krajek** [comment]
Hi @axbutler,

For now, there is no way to influence the name of the properties. To be precise, names are not always in pascal case notation, but rather they are spelled exactly as they are defined in the code. If you would name exception properties using lower case notation this is how they would be logged.

The only property name that you can influence is the "ExceptionDetail" itself which can be set using `IDestructuringOptions.RootName`. On the other hand, in Serilog architecture it seems that it is the role of the sink itself to format the output accordingly. I can imagine that you could create a sink enforcing lower case notation for your properties.

As for the merging with other properties, we had this discussion in the past and in general, found out that having separate `ExceptionDetail` is the only sensible way. Note, that we do not know ahead of time what kind of object we will need to destructure. It may have a property with name conflicting with standard properties. It may contain collections with cyclic references. We have chosen to be robust in all cases.

**Comment by axbutler** [comment]
@krajek Thank you for taking the time to respond to me.
I have a follow-up question if that's okay - what makes Serilog.Exceptions different to the normal Serilog processing that it's properties are serialized as PascalCase where Serilog serializes as camelCase, to the same sink?
If I look at a nested exception from Serilog then I see
```
exception.innerException.innerException.Source
```
The property name ended up PascalCased (which is unfortunate) but the innerException ends up as camelCased
If I look at the same property from Serilog.Exceptions then it becomes:
```
ExceptionDetails.InnerException.InnerException.Source
```
ie, PascalCased for both the property name and the "InnerException" part of it.

Just trying to understand how it works.
I guess it could be that the sink detected Exception and does something special with that?

thanks

**Comment by axbutler** [comment]
Thanks @krajek
